### ISSUE TITLE
Specimen Portal Translator Todo

### ISSUE THREAD

**Issue by puja-trivedi** [brain-bican/bkbit#21]
- [ ] add generation of orange boxes
- [ ] use correct prov attribute for parents for blue boxes
- [ ] use schemaview to get metadata about model rather than manually creating mappings (goal: remove need of bican_to_nimp.csv)
- [ ] add "fail" tests (tests that purposely fail/ raise exceptions/errors)
- [ ] add test for each function
